### ISSUE TITLE
Improve API for cranking

### ISSUE THREAD

**Issue by yuhanfang** [foonetic/solarium#15]
`consume_events_loop` currently runs for some number of milliseconds. This is suboptimal because it either leads to wasted time in the test, or flaky tests if the time is too tight. An event-driven API may be better, where we keep the loop running async and keep it up until an event is consumed.

```rust
let event = something();
let loop = foo.consume_events_loop();
event.block_until_consumed();
loop.kill();
```

**Comment by rohanp9000** [comment]
This was fixed in #17 , we can now crank the first `n` events.
